plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zwegen.nutri'
    compileSdk 34

    defaultConfig {
        applicationId 'com.zwegen.nutri'
        minSdk 24
        targetSdk 34
        versionCode 1848
        versionName '1.848'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}
